version: '3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: tapp41k/taski_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: tapp41k/taski_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/static
  gateway:
    image: tapp41k/taski_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    ports:
      - 9000:80
